language: c
dist: trusty
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install libcap-dev -qq
  - sudo apt-get install nettle-dev -qq

compiler:
  - gcc
  - clang
env:
  matrix:
    - USE_CAP=true
    - USE_CAP=false
    - USE_IDN=true
    - USE_IDN=false
script: make

